apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Delivery
  template:
    metadata:
      labels:
        app: Delivery
    spec:
      containers:
      - name: Delivery
        image: ghcr.io/kun99/p4/delivery:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: DeliveryService
spec:
  selector:
    app: DeliveryService
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP