apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: ghcr.io/kun99/p4/delivery:latest
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DB
              value: p4
            - name: HOST
              value: rabbitmq
            - name: PORT
              value: "5672"
      imagePullSecrets:
        - name: p2secret
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
