apiVersion: apps/v1
kind: Deployment
metadata:
  name: Order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Inventory
  template:
    metadata:
      labels:
        app: Inventory
    spec:
      containers:
      - name: Inventory
        image: ghcr.io/kun99/p4/inventory:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: InventoryService
spec:
  selector:
    app: InventoryService
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP