apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: ghcr.io/kun99/p4/main:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /app/data
          env:
            - name: HOST
              value: rabbitmq-service
            - name: PORT
              value: "5672"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: volume-p4
      imagePullSecrets:
        - name: p2secret
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: main
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-p4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi