apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DB
              value: p4
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-c
              mountPath: /etc/mysql/conf.d
              readOnly: true
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-init
          configMap:
            name: mysql-init
        - name: mysql-c
          configMap:
            name: mysql-c
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS p4;
    USE p4;
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255),
        credits INT
    );
    CREATE TABLE IF NOT EXISTS orders (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        user VARCHAR(255)
    );
    CREATE TABLE IF NOT EXISTS payments (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        order_id INT
    );
    CREATE TABLE IF NOT EXISTS inventory (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255),
        quantity INT
    );
    INSERT IGNORE INTO inventory (name, quantity)
        VALUES ('tokens', 100);
    CREATE TABLE IF NOT EXISTS deliveries (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        order_id INT,
        payment_id INT
    );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-c
data:
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
