apiVersion: apps/v1
kind: Deployment
metadata:
  name: Order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Order
  template:
    metadata:
      labels:
        app: Order
    spec:
      containers:
      - name: Order
        image: ghcr.io/kun99/p4/order:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: OrderService
spec:
  selector:
    app: OrderService
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP